#!/bin/bash

ssh hzheng@tlab036.clamv.jacobs-university.de
ssh hzheng@tlab037.clamv.jacobs-university.de
ssh hzheng@tlab038.clamv.jacobs-university.de
ssh hzheng@tlab039.clamv.jacobs-university.de
ssh hzheng@tlab040.clamv.jacobs-university.de
ssh hzheng@tlab041.clamv.jacobs-university.de
ssh hzheng@tlab042.clamv.jacobs-university.de
ssh hzheng@tlab043.clamv.jacobs-university.de
ssh hzheng@tlab044.clamv.jacobs-university.de
ssh hzheng@tlab045.clamv.jacobs-university.de
ssh hzheng@tlab046.clamv.jacobs-university.de
ssh hzheng@tlab047.clamv.jacobs-university.de
ssh hzheng@tlab048.clamv.jacobs-university.de
ssh hzheng@tlab049.clamv.jacobs-university.de
ssh hzheng@tlab050.clamv.jacobs-university.de
ssh hzheng@tlab051.clamv.jacobs-university.de
ssh hzheng@tlab052.clamv.jacobs-university.de
ssh hzheng@tlab053.clamv.jacobs-university.de
ssh hzheng@tlab054.clamv.jacobs-university.de
ssh hzheng@tlab055.clamv.jacobs-university.de
ssh hzheng@tlab056.clamv.jacobs-university.de
ssh hzheng@tlab057.clamv.jacobs-university.de
ssh hzheng@tlab058.clamv.jacobs-university.de
ssh hzheng@tlab059.clamv.jacobs-university.de
ssh hzheng@tlab060.clamv.jacobs-university.de
ssh hzheng@tlab061.clamv.jacobs-university.de
ssh hzheng@tlab062.clamv.jacobs-university.de
ssh hzheng@tlab063.clamv.jacobs-university.de
ssh hzheng@tlab064.clamv.jacobs-university.de
ssh hzheng@tlab065.clamv.jacobs-university.de
ssh hzheng@tlab066.clamv.jacobs-university.de
ssh hzheng@tlab067.clamv.jacobs-university.de
ssh hzheng@tlab068.clamv.jacobs-university.de
ssh hzheng@tlab069.clamv.jacobs-university.de
ssh hzheng@tlab070.clamv.jacobs-university.de
ssh hzheng@tlab071.clamv.jacobs-university.de
